In [8]:
from DataGenerator import *
import torch

In [9]:
def dm(x):
    batch = x.size()[0] if len(x.size()) > 2 else 1
    m = x

    if batch > 2:
        m = sum(m.matmul(m.permute(0, 2, 1)))

    diag = m.diag().unsqueeze(0).expand_as(m)
    return m * -2 + diag + diag.t()

In [10]:
a = get_coordinates((5, 2), 1, 0, 5)
b = get_distance_matrices(a)



In [11]:
print(b.size())
c = b.view(1, 5, 5, 5) # batch, x, y
print(c.size())

torch.Size([5, 5, 5])
torch.Size([1, 5, 5, 5])


In [12]:
conv1 = torch.nn.Conv2d(
in_channels=5,           # input shape 
out_channels=5,          # output shape
kernel_size=2
)

r_conv1 = torch.nn.ConvTranspose2d(
in_channels=5,           # input shape 
out_channels=5,          # output shape
kernel_size=2
)

ll = torch.nn.Linear(in_features=5, out_features=2, bias=True)

In [14]:
d = ll(r_conv1(conv1(c)))

In [15]:
dm(a)

tensor([[0.0000, 1.4875, 1.4956, 1.3903, 0.9427],
        [1.4875, 0.0000, 1.8371, 2.3200, 2.2674],
        [1.4956, 1.8371, 0.0000, 2.2440, 2.1130],
        [1.3903, 2.3200, 2.2440, 0.0000, 1.8982],
        [0.9427, 2.2674, 2.1130, 1.8982, 0.0000]])

In [17]:
dm(d[0])

tensor([[0.0000, 0.0888, 0.1734, 0.0720, 0.1654],
        [0.0888, 0.0000, 0.1302, 0.1096, 0.1249],
        [0.1734, 0.1302, 0.0000, 0.0634, 0.2276],
        [0.0720, 0.1096, 0.0634, 0.0000, 0.1299],
        [0.1654, 0.1249, 0.2276, 0.1299, 0.0000]], grad_fn=<AddBackward0>)

In [20]:
sum(b) ** 0.5

tensor([[0.0000, 1.7356, 1.6740, 1.7122, 1.5372],
        [1.7356, 0.0000, 1.7922, 1.9090, 1.8414],
        [1.6740, 1.7922, 0.0000, 1.7818, 1.8108],
        [1.7122, 1.9090, 1.7818, 0.0000, 1.7360],
        [1.5372, 1.8414, 1.8108, 1.7360, 0.0000]])

In [ ]:
sum(dm(a))